### ISSUE TITLE
Support variable length Offline Dictionary Indexes for bytes, strings and maps to save on storage

### ISSUE THREAD

**Issue by buchireddy** [winedepot/pinot#24]
**What?**
Currently, the dictionary index for offline segments for bytes and string types uses Fixed-size storage for each value (by picking the size of the max element and padding the smaller elements with "0"). See org.apache.pinot.core.io.util.FixedByteValueReaderWriter 
The idea is to avoid padding and support storing byte arrays/strings/maps of different length while not slowing down the lookups much (obviously).

**Why?**
Fixed size based storage is good for fast lookups but it's very inefficient for the storage. For example, if we have a String column and the size of the biggest string value is 100 bytes but the average size is only 10 bytes, there is about 90% padding. The same thing applies for byte[], maps, etc.

**How?**
Currently, `FixedByteValueReaderWriter` only writes the sorted values in the buffer directly starting from "0" offset and at fixed lengths. So, first Int is at index "0" and the second one at index "4", etc. There is no additional metadata needed in the buffer.
The idea is to maintain the index of each element at the beginning of the buffer so that the element sizes needn't be fixed. When looking up an element from the buffer, we first get it's offset and then read the actual element. This means we do two reads from the buffer (first int offset and then the actual element) but the offset read should be fast enough so it shouldn't slow down the overall operation that much.

Few things to note:
* If all values of a byte[], string or map column have fixed length, this approach rather adds storage overhead and one additional lookup and might not be preferable. Hence, we can have a flag/property at the column level to decide whether to use the VarLengthByteValueReaderWriter or not.
* Backward compatibility shouldn't be broken, which means we need to introduce some kind of header into the buffer to be able to distinguish the on-disk storage format.
* Need to run Benchmarks to see the lookup overhead added by this approach.
* If possible, we should do some benchmarking to get the storage savings with the new approach so that we can make data-driven decisions.

Thanks @kishoreg for pointing this problem and brainstorming.

**Comment by buchireddy** [comment]
FTR, I've done some benchmarking of the new variable length dictionary for strings and compared the numbers with the current FixedLength dictionary and here are the results.

**Time taken to lookup 10M values:**
<img width="882" alt="TimeVsDictionarySizesCharts" src="https://user-images.githubusercontent.com/945283/59487242-edc20280-8e30-11e9-92d7-1891379d4639.png">
**Observation:** As can be clearly seen in the graph, as strings are getting bigger, the variable lengh dictionary is giving much better lookup latencies. When the dictionary size (cardinality) is >1M and the string sizes are small (<100), FixedLength dictionary has better lookup latencies though. 

**Storage requirements of VarLength dictionary:**
Since the variable length dictionary doesn't do any padding, it saves the space for all the cases where the strings in the dictionary aren't of equal length. Hence, this graph plots the % storage savings with VarLength dictionary instead of absolute values.
<img width="612" alt="DictSizeVsStorageSavingsChart" src="https://user-images.githubusercontent.com/945283/59487464-9ff9ca00-8e31-11e9-9e60-13228766662e.png">
**Observation:** If the strings in the dictionary are of different lengths, VarLength dictionary saves 40% space compared to the fixed length dictionary. 

P.S: All raw values from the benchmarking are available at https://docs.google.com/spreadsheets/d/1iOLyhD4AUZw3JsdOkmH6h36KWYalVeUBIVcty6Pnv0E/edit?usp=sharing so feel free to copy/comment on the results.

**Comment by mayankshriv** [comment]
This is great analysis, thanks a lot. Wondering if there was any comparison done with NoDictionary indexing? Each one of them would have a sweet spot of their own (as you pointed out), would be good to have the sweet-spot for NoDictionary indexing as well. I'd expect it to be when there is:
1. Larger variance in string lengths.
2. High cardinality
3. Two levels of re-direction due to dictionary leads to loss of locality.

Also, the storage savings (40% in your case) is a function of string length variance, and may vary from case to case.

**Comment by buchireddy** [comment]
@mayankshriv Sorry I missed replying to this earlier. I've only compared the fixed and variable sized dictionary as of now. If you can give more background and think it's required for more enhancements, I can do that.

> Also, the storage savings (40% in your case) is a function of string length variance, and may vary from case to case.

Yes. Please see the results where the variations and stdDev of values is also present along with the storage savings.

**Comment by buchireddy** [comment]
Merged the PR to this repo as well as the main Pinot repo. Though there are some extra commits in the main repo's PR, we have decided not to cherry-pick those back to this repo.
Closing this issue since the feature is merged.
